#visulation macro for sec Detector
/vis/open OGL 600x600-0+0

/vis/viewer/set/autoRefresh true
/vis/verbose errors

#draw the detector
/vis/drawVolume
/vis/viewer/set/viewpointVector  -1 -1 -1
/vis/viewer/set/lightsVector -1 -1 -1

#draw the events
/vis/trajectories/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

#set colors for the trajectories for different particles
/vis/modeling/trajectories/create/drawByParticleID-0
/vis/modeling/trajectories/drawByParticleID-0/set gamma purple

#add scale, axes, dates, etc.
/vis/scene/add/scale
/vis/scene/add/axes
/vis/scene/add/date

/vis/scene/endOfEventAction accumulate
